spring:
  application:
    name: servicio-personas
server:
  port: 0
  servlet:    context-path: /personas
eureka:  client:    service-url:      defaultZone: http://localhost:8761/eureka
  instance:    ip-address: 10.2.4.12
    prefer-ip-address: true
    instance-id: 10.2.4.12:${server.port}-${random.value}