spring:
  application:
    name: servicio-cliente-personas
server:
  port: 8010
eureka:  client:
    register-with-eureka: false    service-url:      defaultZone: http://localhost:8761/eureka
      