spring:
  application:
    name: servicio-cliente-viajes
server:
  port: 8800
eureka:  client:
    register-with-eureka: false    service-url:      defaultZone: http://localhost:8761/eureka
      